---
- hosts: all
- name: Create Admin User
  user:
    name={% verbatim %}{{ admin_name }}{% endverbatim %}
    password={% verbatim %}{{ admin_password }}{% endverbatim %}
    groups=sudo
    append=yes
    shell=/bin/bash

- name: Add Admin Authorized Key
  authorized_key:
    user={% verbatim %}{{ admin_name }}{% endverbatim %}
    key="{% verbatim %}{{ common_public_key }}{% endverbatim %}"
    state=present

