---
- hosts: all
- name: Create Admin User
  user:
    name=admin
    password={% verbatim %}{{ admin_password }}{% endverbatim %}
    groups=sudo
    append=yes
    shell=/bin/bash

- name: Add Admin Authorized Key
  authorized_key:
    user=admin
    key="{% verbatim %}{{ common_public_key }}{% endverbatim %}"
    state=present

- name: Create Deploy User
  user:
    name=deploy
    password={% verbatim %}{{ deploy_password }}{% endverbatim %}
    groups=www-data
    append=yes
    shell=/bin/bash

- name: Add Deployer Authorized Key
  authorized_key:
    user=deploy
    key="{% verbatim %}{{ common_public_key }}{% endverbatim %}"
    state=present
