---
- hosts: all
- name: Create Admin User
  user:
    name={{ admin_name }}
    password={{ admin_password }}
    groups=sudo
    append=yes
    shell=/bin/bash

- name: Add Admin Authorized Key
  authorized_key:
    user={{ admin_name }}
    key="{{ common_public_key }}"
    state=present

